import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Movie from './models/Movie.js';

dotenv.config();

// trailerUrl = YouTube video ID veya tam URL
const movies = [
  {
    title: 'Karanlık Sular', slug: 'karanlik-sular',
    description: 'İstanbul\'un karanlık sokaklarında kaybolan bir dedektif, gizli bir örgütün izini sürerken kendi geçmişiyle yüzleşmek zorunda kalır.',
    shortDesc: 'İstanbul\'da gerilim dolu bir dedektif hikayesi.',
    year: 2024, duration: '2s 18dk', rating: '16+', imdbScore: 8.4, matchScore: 97,
    genres: ['Gerilim', 'Dram', 'Suç'], type: 'series', seasons: 3, episodes: 24,
    director: 'Murat Şahin',
    cast: [
      { name: 'Ahmet Kaya', role: 'Dedektif Mert', initials: 'AK', colorClass: 'c1' },
      { name: 'Selin Yıldız', role: 'Dr. Ayşe', initials: 'SY', colorClass: 'c2' },
      { name: 'Can Koç', role: 'Başkomiser', initials: 'CK', colorClass: 'c7' },
      { name: 'Zeynep Arslan', role: 'Gizem', initials: 'ZA', colorClass: 'c4' },
    ],
    posterColor: 'c1', backdropColor: 'c1',
    trailerUrl: 'https://youtu.be/xq2mlFKAKTs?si=WOAsrCeyJGVDanKN',
    featured: true, trending: true, isNew: false, top10Rank: 1,
    tags: ['gerilim', 'istanbul', 'polis'],
  },
  {
    title: 'Gece Kuşu', slug: 'gece-kusu',
    description: 'Gece karanlığında yaşanan bir cinayet, küçük bir kasabanın tüm sırlarını gün yüzüne çıkarır.',
    shortDesc: 'Kasabanın karanlık sırrı.',
    year: 2024, duration: '1s 52dk', rating: '13+', imdbScore: 7.8, matchScore: 94,
    genres: ['Dram', 'Gizem'], type: 'movie',
    director: 'Ayşe Kılıç',
    cast: [
      { name: 'Mert Demir', role: 'Savcı Ali', initials: 'MD', colorClass: 'c2' },
      { name: 'Büşra Öz', role: 'Leyla', initials: 'BÖ', colorClass: 'c5' },
    ],
    posterColor: 'c2', backdropColor: 'c2',
    trailerUrl: 'YoHD9XEInc0',
    featured: false, trending: true, isNew: true, top10Rank: 2,
    tags: ['dram', 'gizem', 'kasaba'],
  },
  {
    title: 'Son Kaçış', slug: 'son-kacis',
    description: 'Yanlış yerde yanlış zamanda bulunan bir adam, hayatını kurtarmak için dünyanın dört bir yanını dolaşmak zorunda kalır.',
    shortDesc: 'Nefes kesen bir aksiyon macerası.',
    year: 2023, duration: '2s 5dk', rating: '13+', imdbScore: 7.2, matchScore: 91,
    genres: ['Aksiyon', 'Macera'], type: 'movie',
    director: 'Kerem Aydın',
    cast: [
      { name: 'Barış Yılmaz', role: 'Emre', initials: 'BY', colorClass: 'c3' },
      { name: 'Deniz Kurt', role: 'Ajan Sara', initials: 'DK', colorClass: 'c9' },
    ],
    posterColor: 'c3', backdropColor: 'c3',
    trailerUrl: 'gbRom_uqkVU',
    featured: false, trending: true, isNew: false, top10Rank: 3,
    tags: ['aksiyon', 'macera'],
  },
  {
    title: 'Kırmızı Perde', slug: 'kirmizi-perde',
    description: 'Bir tiyatro topluluğunun içinde birbirini izleyen gizemli olaylar, sahne arkasındaki tehlikeli gerçekleri gün yüzüne çıkarır.',
    shortDesc: 'Sahnenin arkasındaki karanlık.',
    year: 2024, duration: '1s 48dk', rating: '16+', imdbScore: 8.1, matchScore: 89,
    genres: ['Gerilim', 'Gizem'], type: 'movie',
    director: 'Fatma Çelik',
    cast: [{ name: 'Lale Arslan', role: 'Baş Aktris', initials: 'LA', colorClass: 'c4' }],
    posterColor: 'c4', backdropColor: 'c4',
    trailerUrl: 'WvFsJj0aCZI',
    featured: false, trending: true, isNew: false, top10Rank: 4,
    tags: ['gerilim', 'tiyatro'],
  },
  {
    title: 'Fırtına', slug: 'firtina',
    description: 'Denizde mahsur kalan bir mürettebat, hem doğanın öfkesiyle hem de kendi aralarındaki güvensizlikle mücadele eder.',
    shortDesc: 'Denizin ortasında hayatta kalma mücadelesi.',
    year: 2023, duration: '2s 12dk', rating: '13+', imdbScore: 7.5, matchScore: 86,
    genres: ['Aksiyon', 'Dram'], type: 'movie',
    director: 'Serkan Doğan',
    cast: [{ name: 'Cem Önal', role: 'Kaptan', initials: 'CÖ', colorClass: 'c5' }],
    posterColor: 'c5', backdropColor: 'c5',
    trailerUrl: 'aBuAXNOwgCQ',
    featured: false, trending: false, isNew: false, top10Rank: 5,
    tags: ['aksiyon', 'deniz'],
  },
  {
    title: 'Sır', slug: 'sir',
    description: 'Yıllarca saklanan bir aile sırrı, genç bir kadının başlattığı soruşturmayla yüzeye çıkmaya başlar.',
    shortDesc: 'Ailenin karanlık geçmişi.',
    year: 2024, duration: '1s 38dk', rating: '16+', imdbScore: 8.6, matchScore: 95,
    genres: ['Korku', 'Gerilim'], type: 'series', seasons: 2, episodes: 16,
    director: 'Nilüfer Kaya',
    cast: [{ name: 'Elif Şen', role: 'Naz', initials: 'EŞ', colorClass: 'c6' }],
    posterColor: 'c6', backdropColor: 'c6',
    trailerUrl: 'RlOB3UALvrQ',
    featured: false, trending: true, isNew: true, top10Rank: 6,
    tags: ['korku', 'aile', 'gizem'],
  },
  {
    title: 'Kan Bağı', slug: 'kan-bagi',
    description: 'İki kardeş, babaları öldükten sonra şirketin kontrolü için birbirleriyle amansız bir güç mücadelesine girer.',
    shortDesc: 'Kardeşler arasındaki acımasız rekabet.',
    year: 2023, duration: '2s 25dk', rating: '13+', imdbScore: 7.9, matchScore: 88,
    genres: ['Dram'], type: 'series', seasons: 1, episodes: 10,
    director: 'Okan Yurt',
    cast: [{ name: 'Taner Mert', role: 'Büyük Kardeş', initials: 'TM', colorClass: 'c7' }],
    posterColor: 'c7', backdropColor: 'c7',
    trailerUrl: 'kVpv8-5XWJI',
    featured: false, trending: false, isNew: false, top10Rank: null,
    tags: ['dram', 'aile', 'iş dünyası'],
  },
  {
    title: 'Uzak Işık', slug: 'uzak-isik',
    description: 'Uzayın derinliklerinde kaybolan bir astronot, eve dönmek için yapay zekasıyla birlikte imkânsız bir yolculuğa çıkar.',
    shortDesc: 'Uzayda yalnız bir astronotun mücadelesi.',
    year: 2024, duration: '1s 58dk', rating: '7+', imdbScore: 8.9, matchScore: 92,
    genres: ['Bilim Kurgu', 'Macera'], type: 'movie',
    director: 'Zeynep Kara',
    cast: [{ name: 'Hakan Su', role: 'Astronot Bora', initials: 'HS', colorClass: 'c8' }],
    posterColor: 'c8', backdropColor: 'c8',
    trailerUrl: 'z1vqiv-tMsc',
    featured: false, trending: true, isNew: false, top10Rank: 7,
    tags: ['bilim kurgu', 'uzay'],
  },
  {
    title: 'Köprü', slug: 'kopru',
    description: 'Komşu dairelerinde yaşayan iki yalnız insan, tesadüfen tanışıp birbirlerinin hayatını değiştirmeye başlar.',
    shortDesc: 'İki yalnız ruhun şaşırtıcı buluşması.',
    year: 2023, duration: '1s 42dk', rating: '7+', imdbScore: 7.3, matchScore: 85,
    genres: ['Komedi', 'Romantik'], type: 'movie',
    director: 'Merve Öz',
    cast: [{ name: 'Ece Arslan', role: 'Defne', initials: 'EA', colorClass: 'c9' }],
    posterColor: 'c9', backdropColor: 'c9',
    trailerUrl: 'BEepDHOYBXs',
    featured: false, trending: false, isNew: false, top10Rank: null,
    tags: ['komedi', 'romantik'],
  },
  {
    title: 'Gölge Adam', slug: 'golge-adam',
    description: 'Kimliğini gizleyen bir ajan, tehlikeli bir çifte ajan avına çıkarken kendi geçmişiyle yüzleşmek zorunda kalır.',
    shortDesc: 'Kimlik ve aldatmacanın sınırında.',
    year: 2024, duration: '2s 8dk', rating: '16+', imdbScore: 8.3, matchScore: 96,
    genres: ['Aksiyon', 'Gerilim'], type: 'movie',
    director: 'Burak Akar',
    cast: [{ name: 'Selim Kaya', role: 'Ajan K', initials: 'SK', colorClass: 'c10' }],
    posterColor: 'c10', backdropColor: 'c10',
    trailerUrl: 'qdMZf5HBePQ',
    featured: false, trending: true, isNew: true, top10Rank: 8,
    tags: ['aksiyon', 'ajan'],
  },
  {
    title: 'Yeşil Vadi', slug: 'yesil-vadi',
    description: 'Doğanın kalbinde yaşayan son geleneksel toplulukları keşfeden bir belgesel.',
    shortDesc: 'Doğanın içinde kaybolan insanlık.',
    year: 2024, duration: '1s 20dk', rating: 'G', imdbScore: 7.6, matchScore: 83,
    genres: ['Belgesel', 'Doğa'], type: 'movie',
    director: 'Arzu Demir',
    cast: [],
    posterColor: 'c11', backdropColor: 'c11',
    trailerUrl: 'ux2B1UkKAbE',
    featured: false, trending: false, isNew: true, top10Rank: null,
    tags: ['belgesel', 'doğa'],
  },
  {
    title: 'Kızıl Şafak', slug: 'kizil-safak',
    description: 'Türk-Yunan sınırında geçen bu tarihi dram, iki ailenin onlarca yıl süren husumetini ve beklenmedik barışını anlatıyor.',
    shortDesc: 'Sınırın iki yakasında iki aile.',
    year: 2023, duration: '2s 35dk', rating: '13+', imdbScore: 8.0, matchScore: 90,
    genres: ['Dram', 'Tarih', 'Aksiyon'], type: 'movie',
    director: 'Cengiz Aydın',
    cast: [{ name: 'Yusuf Erkan', role: 'Mehmet', initials: 'YE', colorClass: 'c12' }],
    posterColor: 'c12', backdropColor: 'c12',
    trailerUrl: 'TcMBFSGVi1c',
    featured: false, trending: true, isNew: false, top10Rank: 9,
    tags: ['dram', 'tarih'],
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  await Movie.deleteMany({});
  await Movie.insertMany(movies);
  console.log(`✅ ${movies.length} film eklendi (YouTube fragmanlarıyla)`);
  process.exit(0);
}

seed().catch((err) => { console.error(err); process.exit(1); });